name: flutter_secure_auth
description: "FlutterSecureAuth — BLoC Clean Architecture with JWT, Refresh Token & SSL Pinning"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Networking
  dio: ^5.7.0

  # Secure token storage
  flutter_secure_storage: ^9.2.2

  # Internet connectivity
  connectivity_plus: ^5.0.2

  # Dependency injection
  get_it: ^8.0.2

  # Native splash screen
  flutter_native_splash: ^2.4.7

  # No third-party package needed — jailbreak/root detection
  # is implemented natively in core/security/device_security.dart using dart:io

dependency_overrides:
  path_provider_android: 2.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_native_splash:
  color: "#1a1a2e"
  color_dark: "#1a1a2e"
  image: assets/icons/app_icon.png
  image_dark: assets/icons/app_icon.png
  icon_background_color: "#1a1a2e"
  icon_background_color_dark: "#1a1a2e"
  android_12:
    image: assets/icons/app_icon.png
    icon_background_color: "#1a1a2e"
    image_dark: assets/icons/app_icon.png
    icon_background_color_dark: "#1a1a2e"
    color: "#1a1a2e"
    color_dark: "#1a1a2e"
  web: false

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
